### ISSUE TITLE
Neither the preview comand nor welcome message works if team name has a space in it

### ISSUE THREAD

**Issue by FFdhorkin** [mattermost-community/mattermost-plugin-welcomebot#103] opened 2023-03-27 19:07 UTC
When a new user joins the team, they are not getting the welcome message.

When I type `/welcomebot list`, I get

>Teams for which welcome messages are defined:
> -   Word1 Word2

None of the following work:
- `/welcomebot preview Word1 Word2`
- `/welcomebot preview Word1\ Word2`
- `/welcomebot preview "Word1 Word2"`
- `/welcomebot preview 'Word1 Word2'`
- `/welcomebot preview [Word1 Word2]`

All of the above produce this:
>Please specify a team, for which preview should be made.

Incidentally, the team url is `word1-word2` and that doesn't seem to work either; we tried adding it to the config and when trying to do `/welcomebot preview word1-word2`, it says 
> team word1-word2 has not been found

even though it's in the config. So it doesn't look like the Welcomebot plugin uses the url, but maybe it should, since that would address the spaces issue?

**Comment by FFdhorkin** [comment] 2023-03-27 19:56
We tried temporarily removing the space in the team name... 

`/welcomebot preview Word1Word2` now yields:

> error occured while processing greeting for team Word1Word2: failed to query team `Word1Word2`: `GetTeamByName: Unable to find the existing team.,`

**Comment by Kshitij-Katiyar** [comment] 2024-04-16 10:47
@FFdhorkin Here, the slug name for the teams and the channels are used so if you have a team name with a space in it. Always use the slug name for that which you can get from either the URL or from the system console settings. 
https://<mm-url>/<team-slug>/channels/<channel-slug>. 
The same slug name should be used in the config.json setting as well as in the slash command 
/welcomebot preview <team-slug-name>

I have tested the same and it is working fine.
cc: @mickmister

**Comment by mickmister** [comment] 2024-04-16 23:44
@Kshitij-Katiyar Can you verify this with the data in the issue description? Just to be sure

If you are confident this isn't an issue, then we can close the issue

**Comment by Kshitij-Katiyar** [comment] 2024-04-17 13:16
@mickmister @FFdhorkin The only way we can reproduce this is if the user explicitly uses the team name in the config.json file instead of the team-slug. Because /welcomebot list command just picks the team name from the config.json and does not check whether it is correct or not. 
From looking at the issue the user used the team name and not the team slug from the URL. That's why he is encountering the issue. I checked the readme the same thing is stated there as well. 
For the slug-name it is working fine.

**Comment by Kshitij-Katiyar** [comment] 2024-07-19 10:01
@FFdhorkin @mickmister Closing the issue as it is not reproducible.

**Closed by Kshitij-Katiyar** 2024-07-19 10:01 UTC
Labels: Type/Bug
